sudo: required
language: bash

services:
- docker

branches:
  only:
  - master

script:
- echo $DOCKER_USERNAME
- make push-aws-kubectl-helm
- make push-golang-terraform

after_script:
- docker images